[package]
name = "rayon-cond"
version = "0.1.0"
authors = ["Josh Stone <cuviper@gmail.com>"]
description = "Experimental iterator wrapper that is conditionally parallel or serial."
license = "Apache-2.0/MIT"
readme = "README.md"

[dependencies]
rayon = "1.0.2"
itertools = "0.7.8"
either = "1.5.0"
